# Generated by Django 6.1 on 2026-09-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_alter_item_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergens',
            options={'verbose_name': 'Alergeno', 'verbose_name_plural': 'Alergenos'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
